[package]
name = "video-player-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
env_logger = "0.11"
pollster = "0.3"
bytemuck = { version = "1.14", features = ["derive"] }

winit = "0.29"
wgpu = "0.19"

video-sys = "0.1.0"
