entry_point: 261271
non_volatile_global_count: 1915
volatile_global_count: 1990
game_mode: 7
game_title: アストラエアの白き永遠 ver1.1
syscalls:
- id: 26
  name: HistorySet
  args_count: 2
- id: 41
  name: MenuMessSkip
  args_count: 1
- id: 23
  name: GraphRGB
  args_count: 4
- id: 37
  name: InputSetClick
  args_count: 0
- id: 97
  name: Snow
  args_count: 18
- id: 117
  name: TextFontSet
  args_count: 1
- id: 1
  name: AudioPlay
  args_count: 2
- id: 52
  name: MotionMoveRStop
  args_count: 1
- id: 44
  name: MotionAlphaTest
  args_count: 1
- id: 47
  name: MotionAnimTest
  args_count: 1
- id: 115
  name: TextFontGet
  args_count: 0
- id: 146
  name: V3DSet
  args_count: 3
- id: 108
  name: SysAtSkipName
  args_count: 2
- id: 42
  name: MotionAlpha
  args_count: 6
- id: 86
  name: PrimSetText
  args_count: 4
- id: 90
  name: PrimSetXY
  args_count: 3
- id: 79
  name: PrimSetDraw
  args_count: 2
- id: 125
  name: TextShadowDist
  args_count: 2
- id: 9
  name: ControlPulse
  args_count: 0
- id: 107
  name: SoundVol
  args_count: 3
- id: 145
  name: V3DMotionTest
  args_count: 0
- id: 31
  name: InputGetDown
  args_count: 0
- id: 77
  name: PrimSetAlpha
  args_count: 2
- id: 55
  name: MotionMoveS2Stop
  args_count: 1
- id: 96
  name: SaveWrite
  args_count: 1
- id: 18
  name: FlagGet
  args_count: 1
- id: 81
  name: PrimSetOP
  args_count: 3
- id: 57
  name: MotionMoveZ
  args_count: 6
- id: 129
  name: TextSpeed
  args_count: 2
- id: 32
  name: InputGetEvent
  args_count: 0
- id: 76
  name: PrimHit
  args_count: 2
- id: 40
  name: Load
  args_count: 1
- id: 48
  name: MotionMove
  args_count: 8
- id: 60
  name: MotionPause
  args_count: 2
- id: 113
  name: TextFont
  args_count: 3
- id: 25
  name: HistoryGet
  args_count: 2
- id: 116
  name: TextFontName
  args_count: 1
- id: 114
  name: TextFontCount
  args_count: 0
- id: 49
  name: MotionMoveStop
  args_count: 1
- id: 19
  name: FlagSet
  args_count: 2
- id: 24
  name: IntToText
  args_count: 2
- id: 22
  name: GraphLoad
  args_count: 2
- id: 87
  name: PrimSetTile
  args_count: 6
- id: 8
  name: ControlMask
  args_count: 1
- id: 82
  name: PrimSetRS
  args_count: 3
- id: 27
  name: InputFlash
  args_count: 0
- id: 33
  name: InputGetRepeat
  args_count: 0
- id: 67
  name: PartsMotionPause
  args_count: 2
- id: 78
  name: PrimSetBlend
  args_count: 2
- id: 98
  name: SnowStart
  args_count: 2
- id: 131
  name: TextTest
  args_count: 1
- id: 62
  name: MovieState
  args_count: 1
- id: 134
  name: ThreadRaise
  args_count: 1
- id: 102
  name: SoundPlay
  args_count: 3
- id: 0
  name: AudioLoad
  args_count: 2
- id: 16
  name: ExitDialog
  args_count: 0
- id: 109
  name: SysProjFolder
  args_count: 1
- id: 63
  name: MovieStop
  args_count: 0
- id: 101
  name: SoundMasterVol
  args_count: 1
- id: 137
  name: ThreadWait
  args_count: 1
- id: 28
  name: InputGetCursIn
  args_count: 0
- id: 135
  name: ThreadSleep
  args_count: 1
- id: 15
  name: DissolveWait
  args_count: 1
- id: 11
  name: CursorMove
  args_count: 3
- id: 53
  name: MotionMoveRTest
  args_count: 1
- id: 105
  name: SoundType
  args_count: 2
- id: 38
  name: LipAnim
  args_count: 8
- id: 122
  name: TextPos
  args_count: 3
- id: 83
  name: PrimSetRS2
  args_count: 4
- id: 132
  name: ThreadExit
  args_count: 1
- id: 99
  name: SnowStop
  args_count: 2
- id: 139
  name: TimerSet
  args_count: 2
- id: 143
  name: V3DMotionPause
  args_count: 1
- id: 7
  name: ColorSet
  args_count: 5
- id: 59
  name: MotionMoveZTest
  args_count: 1
- id: 111
  name: TextClear
  args_count: 1
- id: 51
  name: MotionMoveR
  args_count: 6
- id: 13
  name: Debmess
  args_count: 2
- id: 119
  name: TextFunction
  args_count: 4
- id: 94
  name: SaveThumbSize
  args_count: 2
- id: 4
  name: AudioStop
  args_count: 2
- id: 110
  name: TextBuff
  args_count: 3
- id: 35
  name: InputGetUp
  args_count: 0
- id: 12
  name: CursorShow
  args_count: 1
- id: 106
  name: SoundTypeVol
  args_count: 2
- id: 141
  name: TitleMenu
  args_count: 1
- id: 133
  name: ThreadNext
  args_count: 0
- id: 93
  name: SaveCreate
  args_count: 2
- id: 2
  name: AudioSilentOn
  args_count: 1
- id: 71
  name: PartsSelect
  args_count: 2
- id: 74
  name: PrimGroupMove
  args_count: 2
- id: 91
  name: PrimSetZ
  args_count: 2
- id: 95
  name: SaveData
  args_count: 3
- id: 5
  name: AudioType
  args_count: 2
- id: 138
  name: TimerGet
  args_count: 2
- id: 54
  name: MotionMoveS2
  args_count: 8
- id: 58
  name: MotionMoveZStop
  args_count: 1
- id: 120
  name: TextOutSize
  args_count: 3
- id: 17
  name: ExitMode
  args_count: 1
- id: 85
  name: PrimSetSprt
  args_count: 4
- id: 66
  name: PartsMotion
  args_count: 3
- id: 103
  name: SoundSilentOn
  args_count: 1
- id: 121
  name: TextPause
  args_count: 2
- id: 75
  name: PrimGroupOut
  args_count: 1
- id: 43
  name: MotionAlphaStop
  args_count: 1
- id: 73
  name: PrimGroupIn
  args_count: 2
- id: 88
  name: PrimSetUV
  args_count: 3
- id: 100
  name: SoundLoad
  args_count: 2
- id: 34
  name: InputGetState
  args_count: 0
- id: 104
  name: SoundStop
  args_count: 2
- id: 61
  name: Movie
  args_count: 2
- id: 128
  name: TextSpace
  args_count: 3
- id: 89
  name: PrimSetWH
  args_count: 3
- id: 68
  name: PartsMotionStop
  args_count: 1
- id: 127
  name: TextSkip
  args_count: 2
- id: 50
  name: MotionMoveTest
  args_count: 1
- id: 144
  name: V3DMotionStop
  args_count: 0
- id: 46
  name: MotionAnimStop
  args_count: 1
- id: 80
  name: PrimSetNull
  args_count: 1
- id: 64
  name: PartsAssign
  args_count: 2
- id: 84
  name: PrimSetSnow
  args_count: 4
- id: 30
  name: InputGetCursY
  args_count: 0
- id: 130
  name: TextSuspendChr
  args_count: 2
- id: 92
  name: Rand
  args_count: 0
- id: 3
  name: AudioState
  args_count: 1
- id: 72
  name: PrimExitGroup
  args_count: 1
- id: 124
  name: TextRepaint
  args_count: 0
- id: 29
  name: InputGetCursX
  args_count: 0
- id: 70
  name: PartsRGB
  args_count: 4
- id: 140
  name: TimerSuspend
  args_count: 1
- id: 39
  name: LipSync
  args_count: 2
- id: 36
  name: InputGetWheel
  args_count: 0
- id: 136
  name: ThreadStart
  args_count: 2
- id: 69
  name: PartsMotionTest
  args_count: 1
- id: 20
  name: FloatToInt
  args_count: 1
- id: 118
  name: TextFormat
  args_count: 7
- id: 142
  name: V3DMotion
  args_count: 6
- id: 123
  name: TextPrint
  args_count: 2
- id: 45
  name: MotionAnim
  args_count: 4
- id: 147
  name: WindowMode
  args_count: 1
- id: 21
  name: GaijiLoad
  args_count: 3
- id: 112
  name: TextColor
  args_count: 4
- id: 14
  name: Dissolve
  args_count: 7
- id: 6
  name: AudioVol
  args_count: 3
- id: 126
  name: TextSize
  args_count: 3
- id: 10
  name: CursorChange
  args_count: 1
- id: 65
  name: PartsLoad
  args_count: 2
- id: 56
  name: MotionMoveS2Test
  args_count: 1
custom_syscall_count: 0
