[package]
name = "lua2hcb_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
encoding_rs = "0.8"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"

